TEMPLATE	= app
LANGUAGE	= C++

INCLUDEPATH	+= .

SOURCES	+= main.cpp \
	mainwindow.cpp \
        xIrcDefaults.cpp

FORMS	= xircform.ui

######################################################################
# Automatically generated by qmake (1.07a) Sat Aug 20 09:05:29 2022
######################################################################


# Input
HEADERS += mainwindow.h xIrcDefaults.h
