TEMPLATE	= app
LANGUAGE	= C++

INCLUDEPATH	+= .

SOURCES	+= main.cpp \
	mainwindow.cpp

FORMS	= xircform.ui actionform.ui nicknameform.ui

######################################################################
# Automatically generated by qmake (1.07a) Sat Aug 20 09:05:29 2022
######################################################################


# Input
HEADERS += mainwindow.h
